DELETE http://localhost:8080/events/1/register
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImVtYWlsQGV4YW1wbGUuY29tIiwiZXhwIjoxNzIxMDM5NjA3LCJ1c2VySWQiOjF9.em6fKfNIJ8wrkfgxSYQfnkQhaOZTZuBFIbtcBqsCq-g