PUT http://localhost:8080/events/2
content-type: application/json

{
    "name":"Event 2 (Updated)",
    "description":"Test event 2",
    "location":"plane",
    "dateTime":"2024-07-14T09:18:00.000Z"
}