name: CI Pipeline

on:
    pull_request:
    push:
        branches:
            - main

permissions:
  id-token: write
  contents: write
  pull-requests: read
  checks: write

concurrency:
    group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
    cancel-in-progress: true

jobs:
    lint:
        name: Linter
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                ref: ${{ github.event.pull_request.head.ref }}
              
            - name: Set up Go
              uses: actions/setup-go@v5
              with:
                #go-version: 1.22.4
                go-version-file: go.mod # read version from go.mod file
            
            - name: golangci-lint
              uses: golangci/golangci-lint-action@v8